import type { JobApplication } from './api'

export const SANDBOX_SEED_APPLICATIONS: JobApplication[] = [
  {
    id: 'sandbox-seed-001',
    title: 'Frontend Engineer',
    company: 'Atlas Labs',
    status: 'applied',
    stage: 'Portfolio review',
    appliedAt: '2024-11-28T15:00:00.000Z',
    location: 'Remote — United States',
    remote: true,
    source: 'Remotive',
    jobPostUrl: 'https://remotive.com/remote-jobs/frontend-engineer',
    notes: 'Sent tailored cover letter focusing on data viz work. Recruiter expects reply by Dec 5.',
    salaryMin: 95000,
    salaryMax: 120000,
    currency: 'USD',
  },
  {
    id: 'sandbox-seed-002',
    title: 'Associate Product Manager',
    company: 'Northwind Systems',
    status: 'interviewing',
    stage: 'Hiring manager sync',
    appliedAt: '2024-11-15T12:00:00.000Z',
    responseAt: '2024-11-20T18:30:00.000Z',
    location: 'Seattle, WA',
    remote: false,
    source: 'LinkedIn',
    jobPostUrl: 'https://www.linkedin.com/jobs/view/123456789',
    notes: 'Preparing product teardown; asked mentor for mock interview this weekend.',
    salaryMin: 105000,
    salaryMax: 135000,
    currency: 'USD',
  },
  {
    id: 'sandbox-seed-003',
    title: 'Data Analyst Intern',
    company: 'Citrus Insights',
    status: 'planned',
    stage: 'Researching team',
    appliedAt: null,
    location: 'Austin, TX',
    remote: false,
    source: 'Company site',
    jobPostUrl: 'https://careers.citrusinsights.com/jobs/data-analyst-intern',
    notes: 'Need to tailor resume with SQL dashboard metrics before applying.',
    salaryMin: 28000,
    salaryMax: 32000,
    currency: 'USD',
  },
  {
    id: 'sandbox-seed-004',
    title: 'Product Design Intern',
    company: 'Orbital Health',
    status: 'offer',
    stage: 'Offer review',
    appliedAt: '2024-10-05T17:45:00.000Z',
    responseAt: '2024-11-01T09:15:00.000Z',
    location: 'Remote — North America',
    remote: true,
    source: 'Portfolio referral',
    jobPostUrl: 'https://orbital.health/design-intern',
    notes: 'Offer expires Dec 10. Negotiating stipend for conference travel.',
    salaryMin: 45000,
    salaryMax: 52000,
    currency: 'USD',
  },
  {
    id: 'sandbox-seed-005',
    title: 'Operations Associate',
    company: 'BrightPath Logistics',
    status: 'rejected',
    stage: 'HR screen',
    appliedAt: '2024-09-20T10:00:00.000Z',
    responseAt: '2024-10-02T20:00:00.000Z',
    location: 'Chicago, IL',
    remote: false,
    source: 'Indeed',
    jobPostUrl: 'https://www.indeed.com/viewjob?jk=brightpath-ops',
    notes: 'Keep relationship warm; recruiter suggested reapplying next hiring cycle.',
    salaryMin: 70000,
    salaryMax: 82000,
    currency: 'USD',
  },
  {
    id: 'sandbox-seed-006',
    title: 'Software Engineering Intern',
    company: 'Parallel Peak',
    status: 'applied',
    stage: 'Recruiter follow-up',
    appliedAt: '2024-11-18T14:30:00.000Z',
    location: 'Denver, CO',
    remote: false,
    source: 'BuiltIn',
    jobPostUrl: 'https://builtin.com/jobs/software-engineering-intern',
    notes: 'Need to send coding sample by Nov 30.',
  },
  {
    id: 'sandbox-seed-007',
    title: 'Growth Marketing Associate',
    company: 'Verve Studio',
    status: 'interviewing',
    stage: 'Case study',
    appliedAt: '2024-11-02T11:00:00.000Z',
    location: 'Remote — US',
    remote: true,
    source: 'AngelList',
    jobPostUrl: 'https://wellfound.com/company/verve/jobs/marketing-associate',
    notes: 'Case study due Friday; highlight lifecycle email wins.',
  },
  {
    id: 'sandbox-seed-008',
    title: 'Backend Engineer',
    company: 'SignalForge',
    status: 'planned',
    stage: 'Drafting outreach',
    appliedAt: null,
    location: 'New York, NY',
    remote: false,
    source: 'Referral',
    jobPostUrl: 'https://signalforge.io/careers/backend-engineer',
    notes: 'Waiting on referral from alumni contact.',
  },
  {
    id: 'sandbox-seed-009',
    title: 'UI Engineer',
    company: 'Lumenary',
    status: 'offer',
    stage: 'Comp negotiation',
    appliedAt: '2024-09-15T09:00:00.000Z',
    responseAt: '2024-10-10T13:00:00.000Z',
    location: 'Remote — Americas',
    remote: true,
    source: 'Twitter DM',
    jobPostUrl: 'https://lumenary.design/jobs/ui-engineer',
    notes: 'Counter-offer sent, waiting on revision.',
    salaryMin: 120000,
    salaryMax: 145000,
    currency: 'USD',
  },
  {
    id: 'sandbox-seed-010',
    title: 'Business Operations Intern',
    company: 'Helio Commerce',
    status: 'applied',
    stage: 'Take-home review',
    appliedAt: '2024-11-09T21:15:00.000Z',
    location: 'Los Angeles, CA',
    remote: false,
    source: 'Handshake',
    jobPostUrl: 'https://helio.com/careers/ops-intern',
    notes: 'Follow-up email scheduled for Dec 2.',
    salaryMin: 32000,
    salaryMax: 36000,
    currency: 'USD',
  },
]
